### ISSUE TITLE
Instalar PHP en Linux

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/theGame#2]
Para poder trabajar en clase.

Bastará lanzar un 
```
su usuario
sudo apt install php
```

**Comment by profeIAP** [comment]
Para probar que funciona podremos lanzar un 

```
php -S localhost:9000 -t .
```

debiendo salir algo parecido a 

![image](https://user-images.githubusercontent.com/16881846/107011770-65783a00-6798-11eb-9cd0-6e17d698aaed.png)

**Comment by luciav4545** [comment]
recent:///559602e0db795c41f10a2b8b601d0935

**Comment by luciav4545** [comment]
![image](https://user-images.githubusercontent.com/58076437/107013047-264ae880-679a-11eb-9bd5-59e07fc0c153.png)
