### ISSUE TITLE
Configurar Phaser

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/theGame#3]
Descargar y descomprimir en una carpeta el código que aparece [en el siguiente tutorial](https://phaser.io/tutorials/making-your-first-phaser-3-game-spanish) de Phaser y comprobar que funciona correctamente.

Para comprobarlo, deberás [arrancar el servidor de PHP](https://github.com/profeIAP/theGame/issues/2#issuecomment-773892860) en la carpeta en la que has descomprimido Phaser y abrir el navegador web con [la siguiente dirección](http://localhost:9000/part9.html) para ver que te aparece el  juego funcionando correctamente

![image](https://user-images.githubusercontent.com/16881846/107013380-8b064300-679a-11eb-84bd-2f0cd9a5c384.png)

**Comment by luciav4545** [comment]
recent:///5dff724df21941f9e5357661601d0d98

**Comment by luciav4545** [comment]
![image](https://user-images.githubusercontent.com/58076437/107014757-55625980-679c-11eb-9409-9f33295f8b8a.png)
